### ISSUE TITLE
Compilation errors when running tests

### ISSUE THREAD

**Issue by Nautigsam** [ebebbington/deno-watch-v2#1]
I see you committed a change to fix tests, but I can not run them.

I use latest version and it does not compile:
```shell
$ deno -V
deno 0.34.0
$ deno run https://raw.githubusercontent.com/ebebbington/deno-watch-v2/master/test/test.ts
< many compilation errors>
```
With which version did you make the tests pass?

**Comment by Nautigsam** [comment]
I finally managed to compile by passing `tsconfig.json` with strict mode disabled.

**Comment by ebebbington** [comment]
I’ll try look into it regardless later today and give an update if I can - disabling strict mode isn’t ideal so I hope to fix whatever caused the problem

**Comment by ebebbington** [comment]
Tests pass on deno version `0.33.0` where as they fail on `0.34.0`. And yes there about a whopping 40 compilation errors. I'm currently trying to fix them on deno `v0.34.0` but there's only so much I can do as I haven't built this project

**Comment by Nautigsam** [comment]
That's good to know! I will stick to v0.33.0 then.

**Comment by ebebbington** [comment]
Again someone shouldn't have to do this, i've cleared down all the errors, i just need to test it properly and i'll make a PR
